### ISSUE TITLE
Error when creating VM

### ISSUE THREAD

**Issue by rwillmer** [BytemarkHosting/bigv-python#16]
I'm trying to create a VM using your playbook as example.

It's failing with this error, any idea why?

/Users/rachel/bitbucket/luzme/devops/ve/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/Users/rachel/.ansible/tmp/ansible-tmp-1438593147.6-79780351145889/bigv-vm", line 1780, in <module>
    main()
  File "/Users/rachel/.ansible/tmp/ansible-tmp-1438593147.6-79780351145889/bigv-vm", line 141, in main
    zone_name=module.params['vm_zone_name'],
KeyError: 'vm_zone_name'

**Comment by jiphex** [comment]
Which platform is this on? Looks like you might be missing the ca-certificates that Python would need to verify the SSL certificate for https://uk0.bigv.io

Could you try the following please and see if you get the same result:

    python -c 'import requests; print(requests.get("https://uk0.bigv.io/definitions"))'

**Comment by rwillmer** [comment]
OSX 10.9.5

Yes I do get the same result.

thanks
Rachel

**Comment by jiphex** [comment]
I'm not really sure what the answer is unfortunately - I think the Requests bundle you're using should come with a certificate bundle that signs our uk0.bigv.io certificate.

We were running a cert with a SHA1 key but that's been updated to one using SHA256 - there's a slim chance it'll work for you now.

**Comment by rwillmer** [comment]
I just had another SSL problem with docker, which appeared to be caused 
by the date on my machine being a couple of minutes slow (even though 
it's supposed to be running ntp, grrr...)

That might be the cause.

I'll try it again next time...

James Hannah wrote:

**Comment by skx** [comment]
The second part of your issue, relating to `vm_zone_name` should be resolved by the pull-request I've just submitted #17

**Comment by jiphex** [comment]
Yeah the VM create should work now I think (Thanks to @skx). If you're still getting the SSL warning though I'm not sure why this might be. Do let us know if you still get the SSL message with the new SHA256 certificate.
